### ISSUE TITLE
Дублирование стейта.

### ISSUE THREAD

**Issue by prodderman** [alyonafomenkova/slider#13]
Почему часть стейта вьюхи продублировано в презентере? Нужно прийти к единому источнику истины:

https://github.com/alyonafomenkova/slider/blob/a077bee5aa8c82ea6467b82a59239b0aef3ebd41/src/plugin/presenter/Presenter.ts#L14-L18

https://github.com/alyonafomenkova/slider/blob/a077bee5aa8c82ea6467b82a59239b0aef3ebd41/src/plugin/view/MainView/ViewModel.ts#L14-L18

**Comment by prodderman** [comment]
Это ишью всю еще не исправлено, в презентере все еще остается часть стейта.
Так же в презентере появилась не свойственная ему логика:
![image](https://user-images.githubusercontent.com/24736776/110448386-bd85c180-80f3-11eb-96cf-fce4665e4142.png)

Презентер должен налаживать коммуникацию между Вью и Моделью, но никак не забирать часть их логики

**Comment by alyonafomenkova** [comment]
@prodderman Тут я не согласна.
Модель содержит бизнесовые (в данном случае необходимые для математических расчетов) данные. Она не должна знать ни про ориентацию, ни про шкалу.
Вью лишь отрисовывает. Она максимально "тупая".
Презентер как раз управляет ими.

**Comment by alyonafomenkova** [comment]
@prodderman и именно дублирование стейта сейчас уже нет.
