### ISSUE TITLE
Условия 

### ISSUE THREAD

**Issue by Olga-Skoroded** [alyonafomenkova/slider#3]
> Все проверки содержащие более одного условия должны быть вынесены. Выносить в отдельную архитектурную единицу - переменную или функцию. [(best-practices)](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.9)

![условия](https://user-images.githubusercontent.com/68814270/96272708-ac2f0200-0ff8-11eb-90f5-0c1c95122119.png)

**Comment by alyonafomenkova** [comment]
@Olga-Skoroded Если по стандартам никак нельзя использовать больше одного условия, то как быть в таких ситуациях?
Я читала, что использовать Non-Null Assertion Operator считается очень плохой практикой.
![image](https://user-images.githubusercontent.com/29568698/96305561-c243bf00-1006-11eb-9e20-9d7a3dcc2797.png)

**Comment by alyonafomenkova** [comment]
Если вынести уловия в отдельную переменную или функцию, то ниже по коду не происходит смарткаст, и компилятор "думает", что проверок не было. 
Чтобы удовлетворить стандартам fsd (не использовать более одного условия) и не вводить `Non-Null Assertion Operator` (плохая практика), приняла решение использовать дополнительные проверки и выброс исключения:
```if (!this.sliderView) throw new Error('Slider view is not defined.');
if (!this.pointerFromView) throw new Error('Pointer from view is not defined.');
if (!this.pointerToView) throw new Error('Pointer to view is not defined.');
if (!this.scaleView) throw new Error('Scale view is not defined.');
```
